TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
DB += Bx9000Info.template
DB += Bx9000InstalledBTs.template
DB += KL1104.template
DB += KL1124.template
DB += KL1408.template
DB += KL2124.template
DB += KL2408.template
DB += KL2502.template
DB += KL2512.template
DB += KL2622.template
DB += KL3064.template
DB += KL3102.template
DB += KL3202.template
DB += KL3204.template
DB += KL3312.template
DB += KL3314.template
DB += KL3408.template
DB += KL3468.template
DB += KL4002.template
DB += KL4132.template



# Also install substitutions files for easy access
DB += Bx9000.substitutions
DB += KL1104.substitutions
DB += KL1124.substitutions
DB += KL1408.substitutions
DB += KL2124.substitutions
DB += KL2408.substitutions
DB += KL2502.substitutions
DB += KL2512.substitutions
DB += KL2622.substitutions
DB += KL3064.substitutions
DB += KL3102.substitutions
DB += KL3202.substitutions
DB += KL3204.substitutions
DB += KL3312.substitutions
DB += KL3314.substitutions
DB += KL3408.substitutions
DB += KL3468.substitutions
DB += KL4002.substitutions
DB += KL4132.substitutions

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

