TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
DB += Bx9000Info.template
DB += Bx9000InstalledBTs.template
DB += KL1104.template
DB += KL1124.template
DB += KL1408.template
DB += KL1488.template
DB += KL2114.template
DB += KL2124.template
DB += KL2408.template
DB += KL2502.template
DB += KL2512.template
DB += KL2622.template
DB += KL3064.template
DB += KL3102.template
DB += KL3022.template
DB += KL3012.template
DB += KL3162.template
DB += KL3202.template
DB += KL3204.template
DB += KL3222.template
DB += KL3312.template
DB += KL3314.template
DB += KL3408.template
DB += KL3468.template
DB += KL4002.template
DB += KL4004.template
DB += KL4132.template

DB += Bx9000-lcls.db
DB += Bx9000Info-lcls.template
DB += Bx9000InstalledBTs-lcls.template
DB += KL1104-lcls.template
DB += KL1124-lcls.template
DB += KL1488-lcls.template
DB += KL1408-lcls.template
DB += KL2114-lcls.template
DB += KL2124-lcls.template
DB += KL2408-lcls.template
DB += KL2872-lcls.template
DB += KL3064-lcls.template
DB += KL3102-lcls.template
DB += KL3022-lcls.template
DB += KL3022-lcls-standalone.template
DB += KL3012-lcls.template
DB += KL3012-lcls-standalone.template
DB += KL3162-lcls.template
DB += KL3202-lcls.template 
DB += KL3222-lcls.template 
DB += KL3314-lcls.template 
DB += KL3408-lcls.template
DB += KL4002-lcls.template
DB += KL4004-lcls.template
DB += KM1004-lcls.template
DB += KM2004-lcls.template

DB += analog-conversion-lcls.template

# Single channel general purpose analog channel
# Does not contain or reference higher-level PV(s)
DB += Bx9000-anlgchan-standalone.db

# For use in conjunction with analog-conversion-lcls.template

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

